- src/cpp/bg_game/battler.cpp
- src/cpp/bg_game/battler.hpp
- src/cpp/bg_game/battler_test.cpp
- src/cpp/bg_game/board.cpp
- src/cpp/bg_game/board.hpp
- src/cpp/bg_game/board_test.cpp
- src/cpp/bg_game/player.cpp
- src/cpp/cards/bgs/BgBaseCard.cpp
- src/cpp/cards/bgs/BgBaseCard.hpp
- src/cpp/cards/bgs/BgCardFactory.cpp
- src/cpp/cards/bgs/BgCardFactory.hpp
- src/cpp/cards/bgs/BgCardFactory_test.cpp
- src/cpp/cards/bgs/DeathrattleCards.cpp
- src/cpp/cards/bgs/DeathrattleCards.hpp
Got some smart pointers working, and even did a few deathrattles to showcase it
> Bgs smart ptr

- src/bgs_engine/bg_game/bobs_tavern.cpp
- src/bgs_engine/bg_game/bobs_tavern.hpp
- src/bgs_engine/bg_game/bobs_tavern_test.cpp
- src/bgs_engine/bg_game/player.hpp
- src/bgs_engine/bg_game/player_test.cpp
CL:
1. Refactored bobs tavern to be a part of the player
2. Added basic turn mechanic
3. Adjusted tavern up mechanic to reflect turn mechanic
4. Cleaned up some dead code and some naming inconsistencies
> Basic turn mechanic

- src/bgs_engine/bg_game/bobs_tavern.cpp
- src/bgs_engine/bg_game/bobs_tavern.hpp
- src/bgs_engine/bg_game/bobs_tavern_test.cpp
- src/bgs_engine/bg_game/player.hpp
- src/bgs_engine/cards/bgs/BgCardFactory.cpp
- src/bgs_engine/cards/bgs/BgCards.cpp
- src/bgs_engine/cards/bgs/BgCards.hpp
CL:
1. Added steward of time (https://hearthstone.gamepedia.com/Steward_of_Time)
2. Updated Freedealing gambler to be a pirate (bug)
> Added steward of time.

- django/login/tests.py
To run django tests, from the root of the docker container run `python manage.py test`.
> Add tests for account registration page

- src/bgs_engine/bg_game/battler.cpp
- src/bgs_engine/bg_game/battler.hpp
- src/bgs_engine/bg_game/battler_test.cpp
- src/bgs_engine/bg_game/player_test.cpp
- src/bgs_engine/cards/bgs/BgBaseCard.cpp
- src/bgs_engine/cards/bgs/BgBaseCard.hpp
- src/bgs_engine/cards/bgs/BgCardFactory.cpp
- src/bgs_engine/cards/bgs/BgCards.cpp
- src/bgs_engine/cards/bgs/BgCards.hpp
A bunch of cards. Still a few to go, but getting there! Close to having all the cards finished.
> More cards (trying to get rest of cards in baseline)

- src/bgs_engine/bg_game/battler_test.cpp
- src/bgs_engine/bg_game/board.hpp
- src/bgs_engine/bg_game/player.hpp
- src/bgs_engine/bg_game/player_test.cpp
- src/bgs_engine/cards/bgs/BgBaseCard.cpp
- src/bgs_engine/cards/bgs/BgBaseCard.hpp
- src/bgs_engine/cards/bgs/BgCardFactory.cpp
- src/bgs_engine/cards/bgs/BgCards.cpp
- src/bgs_engine/cards/bgs/BgCards.hpp
Not really happy about how I did Y'Shaarj, but it'll work for now. Some redesign would be nice around an all-encompassing trigger. Right now the issue is triggers only go off when a card is attacked/defended, and the trigger is tied to the attacker/defender. However there's some interactions (like Y'Shaarj) where another card (not attacker/defender) is affected. These situations are currently not handled well.
> Some of the remaining t4 cards

- src/bgs_engine/bg_game/player.hpp
- src/bgs_engine/bg_game/player_test.cpp
- src/bgs_engine/cards/bgs/BgBaseCard.hpp
- src/bgs_engine/cards/bgs/BgCardFactory.cpp
- src/bgs_engine/cards/bgs/BgCards.cpp
- src/bgs_engine/cards/bgs/BgCards.hpp
Not super happy w/ introducing getters and setters that shouldn't be available (except for this special case), but there is no way to reassign `this`
> Added faceless taverngoer (t5 cards)

- README.md
- web/client/src/App.test.js
- web/client/src/components/Registration.js
- web/django/fixtures/users.json
- web/django/users/tests.py
- Read validation errors from backend and display them on user signup page
- Update django tests
- Update Readme to mention Material-UI
> Add validation errors on user sign up

- src/bgs_engine/bg_game/battler.cpp
- src/bgs_engine/bg_game/battler.hpp
- src/bgs_engine/bg_game/battler_test.cpp
- src/bgs_engine/bg_game/board.cpp
- src/bgs_engine/bg_game/board.hpp
- src/bgs_engine/bg_game/board_test.cpp
- src/bgs_engine/bg_game/bobs_buddy.cpp
- src/bgs_engine/bg_game/bobs_buddy.hpp
- src/bgs_engine/bg_game/bobs_buddy_test.cpp
- src/bgs_engine/bg_game/bobs_tavern.cpp
- src/bgs_engine/bg_game/bobs_tavern_test.cpp
- src/bgs_engine/bg_game/hand.hpp
- src/bgs_engine/bg_game/hero.cpp
- src/bgs_engine/bg_game/hero_factory.cpp
- src/bgs_engine/bg_game/player.hpp
- src/bgs_engine/bg_game/player_test.cpp
- src/bgs_engine/bg_game/rng_singleton.hpp
- src/bgs_engine/bg_game/rng_singleton_test.cpp
- src/bgs_engine/cards/bgs/BgBaseCard.cpp
- src/bgs_engine/cards/bgs/BgBaseCard.hpp
- src/bgs_engine/cards/bgs/BgCardFactory.cpp
- src/bgs_engine/cards/bgs/BgCardFactory.hpp
- src/bgs_engine/cards/bgs/BgCards.cpp
- src/bgs_engine/cards/bgs/BgCards.hpp
Deciding to do a little cleanup to make contributions easier. There's more to come (namely removing dead code and warnings), this is just a start. 
Andrew give this a look and see if your IDE of choice loads it a little bit better...
> Removed tabs, replaced w/ spaces (except in makefiles)

- src/bgs_engine/bg_game/battler.cpp
- src/bgs_engine/bg_game/battler.hpp
- src/bgs_engine/bg_game/battler_test.cpp
- src/bgs_engine/bg_game/board.cpp
- src/bgs_engine/bg_game/board.hpp
- src/bgs_engine/bg_game/bobs_buddy.hpp
- src/bgs_engine/bg_game/bobs_buddy_test.cpp
- src/bgs_engine/bg_game/bobs_tavern.cpp
- src/bgs_engine/bg_game/bobs_tavern.hpp
- src/bgs_engine/bg_game/bobs_tavern_test.cpp
- src/bgs_engine/bg_game/hand.hpp
- src/bgs_engine/bg_game/player.hpp
- src/bgs_engine/bg_game/player_test.cpp
- src/bgs_engine/bg_game/rng_singleton_test.cpp
- src/bgs_engine/cards/bgs/BgBaseCard.cpp
- src/bgs_engine/cards/bgs/BgBaseCard.hpp
- src/bgs_engine/cards/bgs/BgCardFactory.cpp
- src/bgs_engine/cards/bgs/BgCards.cpp
- src/bgs_engine/cards/bgs/BgCards.hpp
> Code cleanup (Removed all warnings and unused code)

- web/django/heart_app/urls.py
- web/django/manage.py
- web/django/requirements.txt
- web/django/users/models.py
- web/django/users/views.py
Add [Prospector](https://pypi.org/project/prospector/) to lint python
> Add Prospector for python linting

- README.md
- web/client/.eslintrc.json
- web/client/package.json
- web/client/src/App.js
- web/client/src/components/Login.js
- web/client/src/components/ProTip.js
- web/client/src/components/Registration.js
- web/client/src/theme.js
- web/client/yarn.lock
Adding [Airbnb](https://airbnb.io/javascript)'s implementation of [ESLint](https://eslint.org/) to provide static JavaScript linting.
> Add ESLint and fix lint errors

- src/bgs_engine/bg_game/bobs_tavern.cpp
- src/bgs_engine/bg_game/bobs_tavern.hpp
- src/bgs_engine/bg_game/player.hpp
- src/bgs_engine/bg_game/player_test.cpp
- src/bgs_engine/cards/bgs/BgBaseCard.hpp
- src/bgs_engine/cards/bgs/BgCards.cpp
- src/bgs_engine/cards/bgs/BgCards.hpp
Lists all possible actions (i.e. all actions that might ever be possible) and all available actions (i.e. actions that can be taken). It essentially represents where you could click or drag something while playing the game, will be useful for the RL side
> List avail actions

- src/bgs_engine/bg_game/board.hpp
- src/bgs_engine/bg_game/player.hpp
- src/bgs_engine/cards/bgs/BgBaseCard.hpp
- src/bgs_engine/cards/bgs/BgCardFactory_test.cpp
In the spirit of CLI work and dumping JSON to interested clients...
> BgBaseCard serialization

- web/client/src/App.js
- web/client/src/components/navbar.js
- web/client/src/index.js
- web/client/src/pages/Login.js
- web/client/src/utils/auth.js
- web/client/src/utils/constants.js
- web/client/src/utils/styles.js
Adding a persistent nav bar at the top of the site
> Add top nav bar

- src/bgs_engine/bg_game/player.hpp
- src/bgs_engine/main.cpp
Usage showing tool can maintain state and reset state:
```
(base) Matthews-MacBook-Pro:bgs_engine matt$ ./bgscli -h
This is a stateful CLI tool for simulating bgs games.
Current impl tracks only two players.
Responses are always JSON.
Usage: ./bgscli (specify only one arg):
--all-possible-actions (dumps all actions as JSON)
Dumps all actions
--p1-state
Dumps player1 current state
--p2-state
Dumps player2 current state
--reset
Resets game
(base) Matthews-MacBook-Pro:bgs_engine matt$ ./bgscli --p1-state
{
"_won_last_turn": true,
"board": null,
"elementals_played_this_turn": 0,
"frozen_minions": [],
"gold": 3,
"hand": null,
"health": 40,
"max_gold": 3,
"max_health": 40,
"name": "Init1",
"next_card_id": 0,
"num_free_refreshes": 0,
"opponents_last_board": null,
"pirates_bought_this_turn": 0, …
```
> CLI updates: Adding in ability to dump current player state, added in two players, and ability to reset game.

- src/bgs_engine/bg_game/bobs_tavern.cpp
- src/bgs_engine/bg_game/bobs_tavern.hpp
- src/bgs_engine/bg_game/player.hpp
- src/bgs_engine/main.cpp
Fixed issue w/ player on stack (tavern held reference to player)
> Added buy action.

- src/bgs_engine/Makefile
- src/bgs_engine/bg_game/board.hpp
- src/bgs_engine/bg_game/bobs_buddy.cpp
- src/bgs_engine/bg_game/bobs_buddy.hpp
- src/bgs_engine/bg_game/bobs_buddy_test.cpp
- src/bgs_engine/bg_game/player.hpp
- src/bgs_engine/bg_game/player_test.cpp
- src/bgs_engine/cards/bgs/BgCardFactory_test.cpp
- src/bgs_engine/utils/pyutils.cpp
- src/bgs_engine/utils/pyutils.hpp
- src/bgs_engine/utils/pyutils_test.cpp
```
(base) Matthews-MacBook-Pro:bgs_engine matt$ ./bgscli --p1-state
{
"_won_last_turn": false,
"board": null,
"elementals_played_this_turn": 0,
"frozen_minions": [],
"gold": 3,
"hand": null,
"health": 40,
"max_gold": 3,
"max_health": 40,
"name": "Init1",
"next_card_id": 0,
"num_free_refreshes": 0,
"opponents_last_board": null,
"pirates_bought_this_turn": 0,
"tavern_is_frozen": false,
"tavern_minions": [
"Selfless Hero",
"Selfless Hero",
"Fiendish Servant"
],
"tavern_tier": 1,
"turns_at_current_tier": 0
}(base) Matthews-MacBook-Pro:bgs_engine matt$ ./bgscli --p1-take-action BUY_2
(base) Matthews-MacBook-Pro:bgs_engine matt$ ./bgscli --p1-state
{
"_won_last_turn": false,
"board": null,
"elementals_played_this_turn": 0,
"frozen_minions": [],
"gold": 0,
"hand": {
"cards": [
{
"attack": 2, …
```
> Added play from hand action

- src/bgs_engine/bg_game/battler.hpp
- src/bgs_engine/cards/bgs/BgCardFactory.cpp
- src/bgs_engine/cards/bgs/BgCardFactory.hpp
- src/bgs_engine/cards/bgs/BgCardFactory_test.cpp
- src/bgs_engine/main.cpp
Added list all cards to cli and wrapper to dump sim results as json.
> Added list all cards to cli and wrapper to dump sim results as json.

- src/bgs_engine/Makefile
- src/bgs_engine/consume_cli.py
- src/bgs_engine/main.cpp
CL: Adds a game loop in python between two players
Known issues: 
1. Board is resetting after every battle (not too hard to fix)
2. Some illegal cards in the pool that can't be bought in-game (trivial to fix)
> Semi-functional game loop

- src/bgs_engine/Makefile
- src/bgs_engine/bg_game/Makefile
- src/bgs_engine/bg_game/battler_test.cpp
- src/bgs_engine/cards/bgs/BgBaseCard.cpp
- src/bgs_engine/cards/bgs/Makefile
Had to do w/ a special harbinger interaction...
> Fixing bug where we were seg faulting if a taunt died last in battle

- src/bgs_engine/bg_game/battler.cpp
- src/bgs_engine/bg_game/battler.hpp
- src/bgs_engine/main.cpp
- src/python/env/bgs_environment.py
- src/python/requirements.txt
- src/python/train.py
Install the requirements.
Make the CLI.
Ray has a dashboard that gives you some performance statistics. When using WSL 2 you have to set the dashboard host to the IP of your WSL VM, so if you look in train.py, you can see in ray.init() where to set the address. If you comment it out it defaults to localhost.
All training runs get logged to ~/ray_results automatically.
Run: python train.py
This will train a DQN policy for player 1 and create a random policy for player 2.
You can view the ray dashboard, but it might be easier to just load up tensorboard directly to look at training performance:
tensorboard --logdir ~/ray_results
> Python RL Environment

- web/client/src/App.js
- web/client/src/components/navbar.js
- web/client/src/pages/Rollout.js
- web/client/src/utils/constants.js
CL:
1. Added a rollout tool page with a simple message
2. Added buttons to nav between that page and the home page
Some proof:
After login:
After naving to rollout by clicking top right rollout tool button:
Looking for ideas on what a meaningful test might be, but seems way too basic to assert anything useful at this particular point.
> Added a rollout page (nothing there yet, just the hook)

- web/client/.eslintignore
- web/client/package.json
- web/client/src/pages/Rollout.js
Pixi is a 2d animation lib, will be use…ful for emulating the battlegrounds game visuals. You'll have to rebuild (`docker-compose build`) to test this out. The pic doesn't do it justice, in reality this damn bunny flies around at nauseating speeds:
> Adding in react pixi example

- web/client/src/pages/Rollout.js
This will eventually be important for clicking through frames.
> Added animation toggle. 

- web/client/src/pages/Rollout.js
Allows for basic filtering on the picker
> Rollout tool card picker
